# Generated by Django 5.0.1 on 2024-03-17 09:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ServiceAdsApp', '0010_ad_image'),
        ('VoteApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='votes',
            unique_together={('ad', 'user')},
        ),
    ]
