# Generated by Django 5.0.1 on 2024-03-22 14:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ServiceAdsApp', '0010_ad_image'),
        ('VoteApp', '0002_alter_votes_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Votes',
            new_name='Vote',
        ),
    ]
