# Generated by Django 5.0.1 on 2024-02-02 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SpecialistApp', '0002_remove_specialist_last_login_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='specialist_id',
            new_name='specialist',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='user_id',
            new_name='user',
        ),
    ]
