# Generated by Django 5.0.1 on 2024-03-13 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SpecialistApp', '0003_rename_specialist_id_rating_specialist_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
