# Generated by Django 5.0.1 on 2024-02-01 07:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServiceAdsApp', '0002_rename_ad_text_ad_text'),
        ('SpecialistApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='specialist_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SpecialistApp.specialist'),
        ),
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('request_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('ad_id_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ServiceAdsApp.ad')),
                ('user_id_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
