# Generated by Django 5.0.1 on 2024-02-02 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ServiceAdsApp', '0004_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user_id_fk',
            new_name='user_fk',
        ),
        migrations.RenameField(
            model_name='servicerequest',
            old_name='ad_id_fk',
            new_name='ad_fk',
        ),
        migrations.RenameField(
            model_name='servicerequest',
            old_name='user_id_fk',
            new_name='user_fk',
        ),
    ]
