# Generated by Django 5.0.1 on 2024-02-09 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServiceAdsApp', '0005_rename_user_id_fk_comment_user_fk_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ad',
            options={},
        ),
        migrations.RemoveField(
            model_name='ad',
            name='slug',
        ),
        migrations.AlterField(
            model_name='ad',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
