# Generated by Django 5.0.1 on 2024-02-11 09:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServiceAdsApp', '0006_alter_ad_options_remove_ad_slug_alter_ad_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='text',
            field=models.TextField(default='text comment test'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='servicerequest',
            unique_together={('ad_fk', 'user_fk')},
        ),
    ]
