# Generated by Django 5.0.1 on 2024-02-13 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ServiceAdsApp', '0008_alter_comment_options_comment_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_at']},
        ),
    ]
