# Generated by Django 5.0.1 on 2024-02-20 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServiceAdsApp', '0009_alter_comment_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='image',
            field=models.ImageField(default=1, upload_to='ad_images/'),
            preserve_default=False,
        ),
    ]
